### ISSUE TITLE
可以分享一下牌组模板吗？自己设置不成功

### ISSUE THREAD

**Issue by huyyi** [aote777/anki-md-template#1]
# 可以分享一下牌组akpg文件吗？
自己设置不成功：

![image.png](https://s2.loli.net/2022/02/20/7W3UrFNRPjKzMsQ.png)

**Comment by aote777** [comment]
> # 可以分享一下牌组akpg文件吗？
> 
> 自己设置不成功：
> 
> ![image.png](https://camo.githubusercontent.com/daf593b26b868a268f6e416f86556fb09b2581509e87bc3d8231ddc555dec3a5/68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30322f32302f3757335572464e52506a4b7a4d73512e706e67)

我没有对mac电脑进行测试,可能就是不兼容吧

**Comment by aote777** [comment]
啊 我看了一下 你的设置模板有问题 , 你看一下我简书的教程吧 , 正常不应该有div的 那个只不过是我在HTML里测试用的东西

**Comment by aote777** [comment]
https://www.jianshu.com/p/57b84a7a3c75

**Comment by aote777** [comment]
akpg 已经传到仓库里了 需要自己下载

**Comment by huyyi** [comment]
确实是兼容性问题，在win下测试成功了，多谢解答！！

![image.png](https://s2.loli.net/2022/02/20/Z2wyf3MODHp4BnQ.png)
