### ISSUE TITLE
网络离线状态下想要使用卡片模板参考

### ISSUE THREAD

**Issue by zhouliuhuo** [aote777/anki-md-template#12]
感谢分享如此实用的模板！！！
但还是想问一下，是否有不联网的解决方案呢？

**Comment by aote777** [comment]
这个问题我想想 。 我在21年好像就是把js库放本地的。后来才改成cdn的形式下载

**Comment by aote777** [comment]
其余的代码就一样了。只是把cdn的那部分去掉了。直接用script标签引用js资源就完事了

**Comment by zhouliuhuo** [comment]
好的，感谢！！！
