### ISSUE TITLE
格式异常

### ISSUE THREAD

**Issue by lnwgxY** [aote777/anki-md-template#13]
# 从viscode复制粘贴到front和back无法正常显示：
![屏幕截图 2024-11-20 123459](https://github.com/user-attachments/assets/ac40f9d0-904e-4593-9974-f46aa0ea6147)

# 但是把viscode里面的内容复制到文本文件.txt在复制到front，back又能正常显示：
![image](https://github.com/user-attachments/assets/9a7b04a9-1700-426e-9114-e5216892a588)

**Comment by aote777** [comment]
你这是把vscode 的样式复制出来了。需要复制为纯文本

**Comment by aote777** [comment]
![图片](https://github.com/user-attachments/assets/f08a0de8-1ce0-4ab7-804e-19baf3c390bf)
如果你想vscode里复制纯文本 不带样式的。设置里把这个勾选去掉
这个问题咱们这个anki卡片应该是不太好处理。考虑的问题比较多
