### ISSUE TITLE
在ios和ipad端的卡片字体会居中显示

### ISSUE THREAD

**Issue by phenixcxz** [aote777/anki-md-template#2]
mac端显示是正常的，但是ios和ipados的软件，markdown显示内容自动居中了

**Comment by aote777** [comment]
> mac端显示是正常的，但是ios和ipados的软件，markdown显示内容自动居中了

额 我没有ios设备 没法测试
你试试在css样式里添加`text-align:left;` 看看行不行 不行的话 我也没办法了 等我卖了ipad我可以再试试

**Comment by aote777** [comment]
> mac端显示是正常的，但是ios和ipados的软件，markdown显示内容自动居中了

我修好了 在body里加了个默认左对齐

```
body {
  margin: 0;
  background:#fff;
width:100%;
height:100%;
text-align:left;
}
···

**Comment by aote777** [comment]
新加了 一个卡片模板的样式代码  直接复制到 anki模板里就行了

**Comment by aote777** [comment]
修好了这个 样式加个左对齐就行了
