### ISSUE TITLE
请求支持夜间模式和MathJax公式渲染

### ISSUE THREAD

**Issue by fjybiocs** [aote777/anki-md-template#3]
## MathJax
使用此模板后，原本anki的KaTeX也无法正常渲染了，请问能否解决这个问题，或支持MathJax渲染。

## 夜间模式
能否支持使用github夜间模式下的Markdown样式。

谢谢

**Comment by aote777** [comment]
你用的啥 客户端 ios? 还是macos 我刚才用手机看了一下 ios夜间模式好使 至于数学公式 这个得等我有空 看看好不好弄

**Comment by aote777** [comment]
mathJax 库已经添加 后续小伙伴可以自行更新代码 核心代码 都在demo.html里 其他的不定期同步

**Comment by OTraveler** [comment]
> 你用的啥 客户端 ios? 还是macos 我刚才用手机看了一下 ios夜间模式好使 至于数学公式 这个得等我有空 看看好不好弄

是只能一直是夜间模式吗，我这边用的win和安卓，不管是白天还是夜间都是以夜间模式展示的

**Comment by aote777** [comment]
> > 你用的啥 客户端 ios? 还是macos 我刚才用手机看了一下 ios夜间模式好使 至于数学公式 这个得等我有空 看看好不好弄
> 
> 是只能一直是夜间模式吗，我这边用的win和安卓，不管是白天还是夜间都是以夜间模式展示的

确实是这样的 因为我只引入了 夜间模式的css库 哈哈哈

这个等我有空改改 很简单也 设备主题监听切换就行

**Comment by aote777** [comment]
> > 你用的啥 客户端 ios? 还是macos 我刚才用手机看了一下 ios夜间模式好使 至于数学公式 这个得等我有空 看看好不好弄
> 
> 是只能一直是夜间模式吗，我这边用的win和安卓，不管是白天还是夜间都是以夜间模式展示的

大兄弟 我已经替换了能识别系统主题的cdn了 你可以对着更新一下
