### ISSUE TITLE
> 你用的啥 客户端 ios? 还是macos 我刚才用手机看了一下 ios夜间模式好使 至于数学公式 这个得等我有空 看看好不好弄

### ISSUE THREAD

**Issue by aote777** [aote777/anki-md-template#5]
> 你用的啥 客户端 ios? 还是macos 我刚才用手机看了一下 ios夜间模式好使 至于数学公式 这个得等我有空 看看好不好弄

是只能一直是夜间模式吗，我这边用的win和安卓，不管是白天还是夜间都是以夜间模式展示的

_Originally posted by @OTraveler in https://github.com/aote777/anki-md-template/issues/3#issuecomment-1831322910_

**Comment by OTraveler** [comment]
> 已经更新替换了 能够自动识别系统主题样式 的 cdn了
好像没有提交代码更改哎

**Comment by aote777** [comment]
> > > > 已经更新替换了 能够自动识别系统主题样式 的 cdn了
> > > 
> > > 
> > > 好像没有提交代码更改哎
> > 
> > 
> > 啊啊 梯子卡了 没提上 再看看
> 
> 试了下安卓端可以啦，win端好像是不支持检测模式会默认浅色，不过无所谓，我习惯win端用深色，自己写了个判断win用深色。 关于cdn的网络问题，提前把这些文件下载到本地，可以通过ankiconnect插件的api上传到anki的媒体库，把网络地址改成媒体名，就可以本地引入啦。

好的  win 设置里有主题跟随系统 可以试试

**Comment by OTraveler** [comment]
> > > > > 已经更新替换了 能够自动识别系统主题样式 的 cdn了
> > > > 
> > > > 
> > > > 好像没有提交代码更改哎
> > > 
> > > 
> > > 啊啊 梯子卡了 没提上 再看看
> > 
> > 
> > 试了下安卓端可以啦，win端好像是不支持检测模式会默认浅色，不过无所谓，我习惯win端用深色，自己写了个判断win用深色。 关于cdn的网络问题，提前把这些文件下载到本地，可以通过ankiconnect插件的api上传到anki的媒体库，把网络地址改成媒体名，就可以本地引入啦。
> 
> 好的 win 设置里有主题跟随系统 可以试试

测试过了，软件问题吧，并没有跟着系统走，一直是浅色。
