### ISSUE TITLE
bug(template): quote block breaking fails in front card

### ISSUE THREAD

**Issue by LemonPrefect** [aote777/anki-md-template#7]
没懂这个问题是怎么产生的，前后卡片的表现不一致。

![image](https://github.com/aote777/anki-md-template/assets/39020700/12114abd-74e3-4f21-a390-ed79ce336740)

**Comment by aote777** [comment]
我看下

**Comment by aote777** [comment]
看了一下showdown 发现已经两年没更新了
我看他真是老糊涂了

直接换了一个解析器

https://github.com/markdown-it/markdown-it

这个问题也解决了

**Comment by LemonPrefect** [comment]
![image](https://github.com/aote777/anki-md-template/assets/39020700/a365e503-5ec6-4993-a7b5-f010b7aaefe7)
