### ISSUE TITLE
导入了您上传好的牌组，使用该牌组中模板生成卡片，代码块中有时会出现&nbsp问题，具体问题如下

### ISSUE THREAD

**Issue by shiningberk** [aote777/anki-md-template#9]
这是anki的答案显示情况：
![image](https://github.com/aote777/anki-md-template/assets/104083632/a40e993a-5a17-4816-a47a-6caf274c51e3)
代码块1是我从网上复制的代码 先复制到我的markdown编辑器里，再导入到anki里面，
我发现行首的空格和中间的空格都出现了&nbsp，行尾的空格没有显示成&nbsp
然后我重新创建了一个代码块2，把代码块1里面的代码复制到代码块2中，然后把空格都删除了，再手打空格补上，导入到anki，发现我删除再手动打上的空格都正常显示了。
这样无法正常使用，记笔记需要从别的地方复制代码到卡片，不可能都手打代码，请您帮我看看是模板的未知bug还是我哪里出错了，万分感谢。
原代码块1的内容如下：
```sql
select  
  a.userkey,  
  a.idno,  
  a.phone,  
  a.name,  
  b.user_active_at,  
  c.intend_commodity,  
  c.intend_rank,  
  d.order_num,  
  d.order_amount  
from user_info a  
left join user_active b on a.userkey = b.userkey  
left join user_intend c on a.phone = c.phone  
left join user_order d on nvl(a.idno,concat(rand(),'idnumber')) = d.idno;
```

**Comment by aote777** [comment]
试了一下  , 可以正常转义空格的 
我也是直接点的复制
可以试试 去除格式的复制吧 , 我复制你GitHub里的 没有nbsp
![图片](https://github.com/aote777/anki-md-template/assets/53163966/2536ceb5-1c4d-49d3-a50a-339f38e5defe)

**Comment by aote777** [comment]
或者复制到微信文件助手发出去 在复制进anki, 可能是原格式有点问题

**Comment by shiningberk** [comment]
@aote777 
您好，感谢您的及时回复，我把这段代码进行各种复制，包括以纯文本格式复制，所展现的结果如下：
![image](https://github.com/aote777/anki-md-template/assets/104083632/fe4f3dde-1869-4942-b528-8eaed8c7003d)
![image](https://github.com/aote777/anki-md-template/assets/104083632/c526a45a-4b51-48b2-8c34-fdc83b661e5a)
![image](https://github.com/aote777/anki-md-template/assets/104083632/55f601c6-28da-4d39-9cdb-ed61a8a42cde)
![image](https://github.com/aote777/anki-md-template/assets/104083632/2e9adfaf-22c6-41d8-83da-e890ba9abcf5)

我把github上的复制到datagrip(idea一个公司开发的，写sql的软件)确实有这个nbsp字符, 
![image](https://github.com/aote777/anki-md-template/assets/104083632/f36ac391-1729-485f-a237-420981fbe3d5)
但是我试过复制到notepad++，微信和typora，在各自的软件上都不显示nbsp，但是一导入到anki就显示nbsp。
我猜测原因是，这段代码本来就存在nbsp，nbsp复制过来自动转换为纯文本，所以以纯文本格式复制不影响，而这几个软件都默认不显示nbsp, 就像datagrip有个设置项关掉就不显示nbsp，但是其实是有的，datagrip的nbsp显示切换开关是这个：
![image](https://github.com/aote777/anki-md-template/assets/104083632/64fc301c-050e-4dd3-aa04-fb2c90cc1924)

目前的解决方法是复制到datagrip，再replace把nbsp替换成空格。

**Comment by aote777** [comment]
嗯嗯  正常代码里不应该有nbsp实体的, 可以看看你复制的那个地方有没有能改的设置

**Comment by shiningberk** [comment]
谢谢老哥
